// field names must be in same order as spreadsheet columns
export const fieldOrder = [
  'key',
  'first',
  'last',
  'nametag',
  'pronouns',
  'email',
  'phone',
  'address',
  'city',
  'state',
  'zip',
  'country',
  'volunteer',
  'housing',
  'scholarship',
  'share',
  // 'dietaryPreferences',
  // 'dietaryRestrictions',
  // 'allergies',
  // 'scent',
  // 'carpool',
  // 'bedding',
  // 'roommate',
  // 'photo',
  'comments',
  'admission',
  'donation',
  'total',
  'deposit',
  'paid',
  'status',
  'purchaser',
  'createdAt',
  'paymentId'
];

export const validFields = [
  ...fieldOrder,
  'people',
  'paymentMethod',
  'receipt',
  'additionalPersonReceipt',
  'emailConfirmation',
  'idempotencyKey'
];
